<?php
declare(strict_types=1);
require_once __DIR__ . '/naa-lib.php';
$in=naa_input();$me=naa_auth($in);$roomId=trim((string)($in['roomId']??''));$targetId=trim((string)($in['userId']??$me['id']));
$room=null;foreach(naa_read('rooms') as $r)if(($r['id']??'')===$roomId){$room=$r;break;}if(!$room)naa_respond(['ok'=>false,'error'=>'Reunião não encontrada.'],404);if(empty($room['certificate']))naa_respond(['ok'=>false,'error'=>'Esta reunião não foi configurada para certificado.'],422);
if($targetId!==($me['id']??'')&&!naa_is_admin($me)&&($room['creatorId']??'')!==($me['id']??'')&&!in_array((string)($me['id']??''),$room['moderators']??[],true))naa_respond(['ok'=>false,'error'=>'Sem permissão.'],403);
$h=null;foreach(naa_read('meeting_history') as $x)if(($x['roomId']??'')===$roomId){$h=$x;break;}if(!$h||empty($h['participants'][$targetId]))naa_respond(['ok'=>false,'error'=>'Participação não encontrada.'],404);$p=$h['participants'][$targetId];
function pt(string $s):string{$e=@iconv('UTF-8','Windows-1252//TRANSLIT',$s);if($e===false)$e=$s;return str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$e);}function dur(int $s):string{$h=intdiv($s,3600);$m=intdiv($s%3600,60);return $h?sprintf('%dh%02d',$h,$m):sprintf('%d min',$m);}function dte(string $x):string{$t=strtotime($x);return $t?date('d/m/Y',$t):'-';}
$logo=dirname(__DIR__).'/logo_nucleo_report.jpg';$jpg=is_file($logo)?file_get_contents($logo):'';$info=$jpg!==''?@getimagesize($logo):false;$has=is_array($info)&&($info[2]??0)===IMAGETYPE_JPEG;
$objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',2=>'<< /Type /Pages /Count 1 /Kids [5 0 R] >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',4=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'];
$imgRef='';if($has){$objects[7]='<< /Type /XObject /Subtype /Image /Width '.(int)$info[0].' /Height '.(int)$info[1].' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '.strlen($jpg)." >>\nstream\n".$jpg."\nendstream";$imgRef=' /XObject << /Im1 7 0 R >>';}
$name=pt((string)($p['name']??'Participante'));$title=pt((string)($room['title']??'LS Meet'));$date=dte((string)($h['startedAt']??$room['startedAt']??$room['createdAt']??''));$time=dur((int)($p['totalSeconds']??0));
$c="q\n".($has?"190 0 0 126 202 650 cm /Im1 Do\n":"")."Q\nBT\n/F4 24 Tf\n165 570 Td (CERTIFICADO DE PARTICIPACAO) Tj\n/F1 13 Tf\n-95 -70 Td (Certificamos que) Tj\n/F4 22 Tf\n0 -42 Td ({$name}) Tj\n/F1 13 Tf\n0 -44 Td (participou da reuniao institucional) Tj\n/F4 18 Tf\n0 -34 Td ({$title}) Tj\n/F1 12 Tf\n0 -44 Td (realizada em {$date}, com tempo conectado de {$time}.) Tj\n0 -90 Td (NAA - Nucleo de Avaliacao da Aprendizagem) Tj\n0 -22 Td (LS Meet 2026 - Desenvolvido por LS System) Tj\nET";
$objects[5]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R /F4 4 0 R >>'.$imgRef.' >> /Contents 6 0 R >>';$objects[6]='<< /Length '.strlen($c)." >>\nstream\n".$c."\nendstream";ksort($objects);$pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";$off=[0];foreach($objects as $n=>$b){$off[$n]=strlen($pdf);$pdf.=$n." 0 obj\n".$b."\nendobj\n";}$xref=strlen($pdf);$max=max(array_keys($objects));$pdf.="xref\n0 ".($max+1)."\n0000000000 65535 f \n";for($i=1;$i<=$max;$i++)$pdf.=sprintf("%010d 00000 n \n",$off[$i]??0);$pdf.="trailer\n<< /Size ".($max+1)." /Root 1 0 R >>\nstartxref\n{$xref}\n%%EOF";
header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="Certificado_LS_Meet.pdf"');header('Content-Length: '.strlen($pdf));header('Cache-Control: no-store');echo $pdf;
